db.url=jdbc:mysql://roundhouse.proxy.rlwy.net:54824/railway?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=zXbgiRQrpJbYnxXyruJxMLNJpueTFitc
db.driver=com.mysql.cj.jdbc.Driver